### ISSUE TITLE
Why forgot about Russian?

### ISSUE THREAD

**Issue by AbraXabra** [carlenlund/techna-sans#2]
Good day!
Why forgot about Russian?
Or politics and then left its mark?

**Comment by carlenlund** [comment]
Thanks for the suggestion! I have added Russian to my todo list.

Closing this as duplicate of #1

**Comment by rellikmil** [comment]
Ahah, besides me, someone else in Russia needs this font.
Never mind, I am ashamed of him.
P. S. don`t forget about Helmet font :)
