### ISSUE TITLE
Stroke contrast should be higher to increase legibility

### ISSUE THREAD

**Issue by carlenlund** [carlenlund/techna-sans#4]
This would make the typeface work better with bigger blocks of text, besides being suited for display use.
Though there's a risk that this clashes with the "charm" of the current, low contrast.

**Comment by rellikmil** [comment]
Offtop: do you know how to make color fonts at FontForge?

**Comment by carlenlund** [comment]
@den32ds great question. It looks like the first step is separating the glyphs into multiple layers, one for each color. But other than that I'm not sure. I found [this article](https://hacks.mozilla.org/2014/10/svg-colors-in-opentype-fonts/) by Mozilla, but it's aimed mainly at the Robofont editor.

**Comment by rellikmil** [comment]
@carlenlund thanks for information. Sad is the fact that in proprietary Glyphs and Fontlab this function exists, but not in FontForge.

**Comment by carlenlund** [comment]
Having thought about this for a while, I think the contrast is okay as it is. Closing this issue for now.
