### ISSUE TITLE
About License for commercial product.

### ISSUE THREAD

**Issue by WuboDev** [carlenlund/techna-sans#8]
Hi

I really like this font! 
I want to use it for my new premium WordPress theme which will sell to others, so, could I bundle it to the theme? If not,  could I host this font on my hosting and only import the font link to the page without bundle it in the theme?

Thanks

**Comment by carlenlund** [comment]
Hi! You are free to bundle the font with your Wordpress theme. I hope you find Techna Sans useful :)

**Comment by WuboDev** [comment]
Awesome! So many thanks!
    	
    	

    	
    
  




On Mon, Feb 17, 2020 at 6:00 AM +0800, "Carl Enlund" <notifications@github.com> wrote:












Closed #8.
